name: flutter_key_value_file_storage
description: An implementation to save big chunks of content to a file
version: 0.0.7
homepage: https://github.com/icapps/flutter_key_value_file_storage

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  device_info_plus: ^11.3.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  path: ^1.8.1
  path_provider: ^2.0.12
  synchronized: ^3.0.1

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.3.2

flutter:
  plugin:
    platforms:
      android:
        package: com.icapps.flutter_key_value_file_storage
        pluginClass: FlutterKeyValueFileStoragePlugin
      ios:
        pluginClass: FlutterKeyValueFileStoragePlugin
